"""The songs guitar players most want to play, most wanted first.

Hand-ranked from what players learn first and look up most (the classic
acoustic and rock repertoire, plus the Israeli songbook). Entries are exact
``song_name`` keys, so a chart never shows two versions of one song; songs
missing from the catalog are simply skipped.
"""

from sqlalchemy import ColumnElement, case

from guitar_player.models.song import Song

WORLD_HITS: tuple[str, ...] = (
    "oasis/wonderwall",
    "bob_dylan/knockin_on_heavens_door",
    "eagles/hotel_california",
    "pink_floyd/wish_you_were_here",
    "led_zeppelin/stairway_to_heaven",
    "the_beatles/let_it_be",
    "vance_joy/riptide",
    "ed_sheeran/perfect",
    "guns_n_roses/sweet_child_o_mine",
    "metallica/nothing_else_matters",
    "leonard_cohen/hallelujah",
    "america/a_horse_with_no_name/na47wMFfQCo",
    "radiohead/creep",
    "the_cranberries/zombie",
    "nirvana/smells_like_teen_spirit",
    "the_animals/house_of_the_rising_sun",
    "white_stripes/seven_nation_army",
    "nirvana/come_as_you_are",
    "jason_mraz/im_yours",
    "the_beatles/hey_jude",
    "van_morrison/brown_eyed_girl/UfmkgQRmmeE",
    "tom_petty/free_fallin/1lWJXDG2i0A",
    "lynyrd_skynyrd/sweet_home_alabama",
    "passenger/let_her_go",
    "ed_sheeran/thinking_out_loud",
    "coldplay/yellow",
    "rem/losing_my_religion/OKvCV8MFIaw",
    "green_day/boulevard_of_broken_dreams",
    "coldplay/viva_la_vida",
    "chris_isaak/wicked_game",
    "adele/someone_like_you",
    "john_lennon/imagine",
    "goo_goo_dolls/iris",
    "kansas/dust_in_the_wind",
    "john_denver/take_me_home_country_roads/uu7j_xljCRY",
    "dolly_parton/jolene/Ixrje2rXLMA",
    "metallica/enter_sandman",
    "deep_purple/smoke_on_the_water",
    "ac_dc/back_in_black",
    "ac_dc/highway_to_hell",
    "red_hot_chili_peppers/under_the_bridge",
    "elvis_presley/cant_help_falling_in_love",
    "queen/bohemian_rhapsody",
    "oasis/dont_look_back_in_anger",
    "simon_garfunkel/the_sound_of_silence",
    "johnny_cash/hurt",
    "creedence_clearwater_revival/have_you_ever_seen_the_rain",
    "creedence_clearwater_revival/bad_moon_rising/zUQiUFZ5RDw",
    "ed_sheeran/photograph",
    "ed_sheeran/shape_of_you",
    "coldplay/fix_you",
    "coldplay/the_scientist",
    "pixies/where_is_my_mind",
    "arctic_monkeys/do_i_wanna_know",
    "arctic_monkeys/505",
    "bon_jovi/livin_on_a_prayer",
    "extreme/more_than_words",
    "bryan_adams/heaven",
    "dire_straits/sultans_of_swing",
    "lewis_capaldi/someone_you_loved",
    "hozier/take_me_to_church",
    "the_lumineers/ho_hey",
    "linkin_park/in_the_end",
    "linkin_park/numb",
    "bob_marley/no_woman_no_cry",
    "cat_stevens/wild_world",
    "the_beatles/yesterday",
    "the_rolling_stones/satisfaction",
    "eric_clapton/layla_acoustic",
    "queen/love_of_my_life",
    "simon_garfunkel/mrs_robinson",
    "the_doors/riders_on_the_storm",
    "the_jimi_hendrix_experience/hey_joe/rXwMrBb2x1Q",
    "george_ezra/budapest",
    "ed_sheeran/castle_on_the_hill",
    "bruno_mars/count_on_me",
    "bruno_mars/when_i_was_your_man",
    "amy_winehouse/back_to_black",
    "tracy_chapman/give_me_one_reason",
    "elton_john/your_song",
    "david_bowie/space_oddity",
    "david_bowie/starman",
    "bob_dylan/like_a_rolling_stone",
    "nirvana/about_a_girl",
    "nirvana/the_man_who_sold_the_world",
    "pearl_jam/even_flow",
    "stone_temple_pilots/plush",
    "alice_in_chains/man_in_the_box",
    "audioslave/like_a_stone",
    "gary_moore/still_got_the_blues",
    "bb_king/the_thrill_is_gone",
    "avril_lavigne/complicated",
    "the_cranberries/linger",
    "oasis/live_forever",
    "foo_fighters/learn_to_fly",
    "foo_fighters/best_of_you",
    "u2/one",
    "shawn_mendes/stitches",
    "taylor_swift/love_story",
    "harry_styles/watermelon_sugar",
    "billie_eilish/happier_than_ever",
    "mumford_sons/little_lion_man",
    "john_mayer/slow_dancing_in_a_burning_room",
    "ac_dc/thunderstruck",
    "sam_cooke/wonderful_world",
)

ISRAELI_HITS: tuple[str, ...] = (
    "arik_einstein/ani_ve_ata",
    "משינה/הכוכבים_דולקים_על_אש_קטנה",
    "איינשטיין_וקלפטר/שביר/cwJtpusMXak",
    "arik_einstein/uf_gozal",
    "שלמה_ארצי/תתארו_לכם",
    "הפיל_הכחול/יסמין",
    "מוניקה_סקס/מכה_אפורה",
    "יציאת_חירום/קחי_לך_זמן",
    "ehud_banai/yerushalayim_shel_barzel",
    "meir_ariel/plonter",
    "mashina/sheleg_be_august",
    "berry_sakharof/nitzotzot",
    "shalom_hanoch/pitom_kam_adam",
    "אביתר_בנאי/עד_מחר",
    "מתי_כספי/ברית_עולם",
    "שלמה_ארצי/ירח",
    "berry_sakharof/mul_ha_tehom",
    "arik_einstein/yesh_bi_ahava",
    "yuval_banai/linshom",
    "yuval_banai/shir_pashut",
    "אריאל_זילבר/שמש_שמש/VE8Azy8T1Ac",
    "חנן_בן_ארי/אמא_אם_הייתי",
    "ehud_banai/be_yom_bahir",
    "shalom_hanoch/lishon_ba_sadot",
    "shalom_hanoch/noladeti_le_shalom",
    "arik_einstein/shir_la_shabbat",
    "arik_einstein/sa_leat",
    "berry_sakharof/agadat_deshe",
    "זוהר_ארגוב/צל_עץ_תמר",
    "עומר_אדם/אחרי_כל_השנים",
    "עומר_אדם/רחוק_מכולם/4g2kexLp2qg",
    "חנן_בן_ארי_וברי_סחרוף/חלליות/lc7rlFdxD0Y",
    "המכשפות/קסם_על_ים_כנרת/Z61CnKaOt3s",
    "מתי_כספי_ויהודית_רביץ/לקחת_את_ידי_בידך",
    "רביב_כנר/רסיסים",
    "אביתר_בנאי/יפה_כלבנה",
    "מאיר_בנאי/גשם",
    "rockfour/חור_בלבנה",
    "יזהר_אשדות/בכל_פעם_שאני_מתאהב_בך_מחדש",
    "יהודית_רביץ/שיר_ללא_שם",
    "גוני_שועלי/עכשיו/NzGDdQ5W1GM",
    "עידן_עמדי/נגמר",
    "מתי_כספי/איך_זה_שכוכב",
    "arik_einstein/layla_layla",
    "מתי_כספי_וריקי_גל/ילדותי_השנייה",
    "חנן_בן_ארי/עטלף_עיוור",
    "שלמה_ובן_ארצי/שיר_פרידה/NeBYphQ3Qy0",
    "דודו_טסה_ורוני_אלטר/מעליות",
    "דניאל_סלומון_ודנה_עדיני/רבות_הדרכים",
    "מאיר_אריאל/עברנו_את_פרעה_נעבור_גם_את_זה",
    "meir_ariel/shir_metorlal",
    "שלמה_ארצי/להציל_אותך",
    "שלמה_ארצי/קצת_משונה_שלא_נשארת",
    "שלמה_ארצי/זה_מה_שנשאר",
)

ALL_HITS: tuple[str, ...] = WORLD_HITS + ISRAELI_HITS


def chart_rank(chart: tuple[str, ...]) -> ColumnElement[int]:
    """0 for the chart's first song, counting up; songs off the chart sort last."""
    return case({key: rank for rank, key in enumerate(chart)}, value=Song.song_name, else_=len(chart))


def is_hit(chart: tuple[str, ...] = ALL_HITS) -> ColumnElement[int]:
    """0 for songs on the chart, 1 otherwise — sorts hits ahead of everything else."""
    return case((Song.song_name.in_(chart), 0), else_=1)
