FROM python:3.13-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY config/ ./config/
COPY src/ ./src/

ENV APP_ENV=prod
ENV HOME=/tmp
ENV PYTHONUNBUFFERED=1
ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONPATH="/app/src"

ENTRYPOINT ["python", "-m", "awslambdaric"]
CMD ["guitar_player.lambdas.unconfirmed_user_cleanup.handler"]
