"""add cascade delete to favorites

Revision ID: 8c3433556813
Revises: 6c4f5a8b2d1e
Create Date: 2026-02-22 09:33:33.843122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c3433556813'
down_revision: Union[str, None] = '6c4f5a8b2d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('favorites_song_id_fkey'), 'favorites', type_='foreignkey')
    op.drop_constraint(op.f('favorites_user_id_fkey'), 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'songs', ['song_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key(op.f('favorites_user_id_fkey'), 'favorites', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('favorites_song_id_fkey'), 'favorites', 'songs', ['song_id'], ['id'])
    # ### end Alembic commands ###
