"""Constants for job processing pipeline."""

import re
from datetime import datetime, timezone

# ---------------------------------------------------------------------------
# Tutorial-link scoring: prefer actual guitar tutorials over music videos
# ---------------------------------------------------------------------------
TUTORIAL_POSITIVE = [
    # English
    "tutorial", "lesson", "how to play", "guitar lesson", "guitar tutorial",
    "strum", "strumming", "strumming pattern", "chords", "chord lesson",
    "beginner", "easy", "play along", "fingerstyle", "acoustic",
    "tab", "tabs", "tablature", "cover lesson", "guitar cover tutorial",
    "learn to play", "teaching", "walkthrough", "breakdown",
    "campfire version", "simplified", "chord chart",
    # Hebrew
    "שיעור", "שיעור גיטרה", "לימוד", "לימוד גיטרה", "איך לנגן",
    "איך מנגנים", "גיטרה", "אקורדים", "פריטה", "טאבים", "לנגן",
    "קאבר שיעור", "הדרכה", "אקורד",
    # Spanish
    "tutorial de guitarra", "cómo tocar", "acordes", "rasgueo",
    "lección", "clase de guitarra",
    # Portuguese
    "aula de violão", "como tocar", "acordes", "cifra",
    # French
    "tutoriel guitare", "comment jouer", "accords", "leçon",
    "cours de guitare",
    # German
    "gitarre lernen", "gitarren tutorial", "wie spielt man", "akkorde",
    # Russian
    "урок гитары", "как играть", "аккорды", "разбор", "на гитаре",
    "табулатура", "перебор",
    # Arabic
    "تعليم جيتار", "درس جيتار", "كوردات", "كيف تعزف",
    # Turkish
    "gitar dersi", "nasıl çalınır", "akorlar",
    # Japanese
    "ギターレッスン", "弾き方", "コード",
    # Korean
    "기타 레슨", "기타 강좌", "코드",
]

TUTORIAL_NEGATIVE = [
    # English
    "official video", "official music video", "music video",
    "lyrics video", "lyric video", "live", "concert", "vevo",
    "live performance", "live session", "full album", "album",
    "karaoke", "instrumental", "remix", "reaction", "review",
    "interview", "behind the scenes", "making of", "visualizer",
    # Hebrew
    "קליפ", "קליפ רשמי", "הופעה", "הופעה חיה", "אלבום",
    "שיר רשמי", "וידאו קליפ",
    # Spanish
    "video oficial", "video musical", "en vivo", "concierto",
    # Portuguese
    "vídeo oficial", "clipe oficial", "ao vivo",
    # French
    "clip officiel", "vidéo officielle", "en concert",
    # German
    "offizielles video", "musikvideo", "live auftritt",
    # Russian
    "официальный клип", "клип", "живое выступление", "концерт",
    # Arabic
    "فيديو كليب", "حفلة",
    # Turkish
    "resmi video", "müzik videosu", "konser",
]

TUTORIAL_DOMAIN_BONUS = [
    "justinguitar.com", "guitartricks.com", "ultimate-guitar.com",
    "guitarlessons.com", "martymusic.com", "andyguitar.co.uk",
]

STEM_EXT = ".mp3"
PROCESS_STARTED_AT = datetime.now(timezone.utc)

# If the API process restarts while a job is PENDING/PROCESSING, the DB can be
# left with an "active" job that no longer has a running background task.
STALE_ACTIVE_JOB_AFTER_SECONDS = 60 * 16  # 16 minutes

# Cooldown for lightweight background tasks (lyrics/merge).
LIGHTWEIGHT_TASK_COOLDOWN_SECONDS = 300  # 5 minutes

# Throttle INFO logs for repeated "blocked" outcomes.
ADMIN_HEAL_LOG_THROTTLE_SECONDS = 600  # 10 minutes

# Bump this to allow a one-time lyrics re-transcription via OpenAI on next deploy.
CURRENT_LYRICS_HEAL_VERSION = 2

# Regex matching characters from non-Latin scripts (Hebrew, Arabic, CJK, etc.)
NON_LATIN_RE = re.compile(
    r"[\u0590-\u05FF\u0600-\u06FF\u0750-\u077F"
    r"\u3000-\u9FFF\uAC00-\uD7AF\u1100-\u11FF]"
)

# Maps demucs output stem names to Song model field base names.
STEM_NAME_MAP: dict[str, str] = {
    "guitar": "guitar",
    "vocals": "vocals",
    "drums": "drums",
    "bass": "bass",
    "piano": "piano",
    "other": "other",
    "guitar_removed": "guitar_removed",
}

# Currently empty -- all stems are kept.
UNWANTED_STEMS: set[str] = set()

DEFAULT_REQUESTED_OUTPUTS = ["guitar_isolated", "vocals_isolated"]

# Demucs service expects *output keys* (e.g. "guitar_isolated"), while the
# frontend and SongService use canonical stem names (e.g. "guitar").
DEMUCS_OUTPUT_KEYS: set[str] = {
    "guitar_isolated",
    "guitar_removed",
    "vocals_isolated",
    "vocals_removed",
}

CANONICAL_TO_DEMUCS_OUTPUT: dict[str, str] = {
    "guitar": "guitar_isolated",
    "guitar_removed": "guitar_removed",
    "vocals": "vocals_isolated",
    "vocals_removed": "vocals_removed",
}

# Canonical stems that are *raw* demucs stems (not requested_outputs keys).
RAW_CANONICAL_STEMS: set[str] = {"drums", "bass", "piano", "other"}

STEM_FILE_VARIANTS: dict[str, list[str]] = {
    "guitar": ["guitar.mp3", "guitar_isolated.mp3"],
    "vocals": ["vocals.mp3", "vocals_isolated.mp3"],
    "drums": ["drums.mp3"],
    "bass": ["bass.mp3"],
    "piano": ["piano.mp3"],
    "other": ["other.mp3"],
}

# Derived stems are generated by post-processing (not by Demucs directly).
DERIVED_STEMS: set[str] = set()

# Thumbnail filenames to scan on disk when the DB key is missing.
THUMB_CANDIDATES = ["thumbnail.jpg", "thumbnail.jpeg", "cover.jpg", "cover.jpeg"]

STEM_LIKE_AUDIO_FILENAMES: set[str] = {
    "vocals.mp3",
    "guitar.mp3",
    "guitar_isolated.mp3",
    "vocals_isolated.mp3",
    "guitar_removed.mp3",
    "vocals_guitar.mp3",
    "drums.mp3",
    "bass.mp3",
    "piano.mp3",
    "other.mp3",
}

LYRICS_CLEANUP_TIMEOUT_S = 30
